// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_PDa6I-7VkgiRl1cDU2jp4pgkarCn8ks',
    appId: '1:486142504172:web:1abf2d38c8f586fe7d49c9',
    messagingSenderId: '486142504172',
    projectId: 'ease-milker-app',
    authDomain: 'ease-milker-app.firebaseapp.com',
    storageBucket: 'ease-milker-app.firebasestorage.app',
    measurementId: 'G-VQFKNDCHR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmJY_vBLUo8AF6WglZlrllX_pqWIl7TY',
    appId: '1:486142504172:android:48648287eddfa40d7d49c9',
    messagingSenderId: '486142504172',
    projectId: 'ease-milker-app',
    storageBucket: 'ease-milker-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKH8yjQbXLxkQQ-hVtxHrhOkUYMK2QRM',
    appId: '1:486142504172:ios:b1ce7ee9b53f02ae7d49c9',
    messagingSenderId: '486142504172',
    projectId: 'ease-milker-app',
    storageBucket: 'ease-milker-app.firebasestorage.app',
    iosBundleId: 'com.example.easemilker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKH8yjQbXLxkQQ-hVtxHrhOkUYMK2QRM',
    appId: '1:486142504172:ios:b1ce7ee9b53f02ae7d49c9',
    messagingSenderId: '486142504172',
    projectId: 'ease-milker-app',
    storageBucket: 'ease-milker-app.firebasestorage.app',
    iosBundleId: 'com.example.easemilker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_PDa6I-7VkgiRl1cDU2jp4pgkarCn8ks',
    appId: '1:486142504172:web:d38f1b75b381ebd67d49c9',
    messagingSenderId: '486142504172',
    projectId: 'ease-milker-app',
    authDomain: 'ease-milker-app.firebaseapp.com',
    storageBucket: 'ease-milker-app.firebasestorage.app',
    measurementId: 'G-E31Q1PV3E6',
  );

}